# Generated by Django 5.2.7 on 2025-11-14 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('guidance', models.BooleanField(default=True)),
                ('travel_type', models.CharField(blank=True, max_length=512, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='RequestRootMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acceptance', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request_root_map',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('guidance', models.BooleanField(default=True)),
                ('travel_type', models.CharField(blank=True, max_length=512, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'root',
            },
        ),
    ]
