# Generated by Django 5.2.7 on 2025-11-06 03:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlaceApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('guidance', models.BooleanField(default=True)),
                ('travel_type', models.CharField(blank=True, max_length=512, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='PlaceApp.travelplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('guidance', models.BooleanField(default=True)),
                ('travel_type', models.CharField(blank=True, max_length=512, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roots', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roots', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'root',
            },
        ),
        migrations.CreateModel(
            name='RequestRootMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acceptance', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='DocumentApp.request')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='DocumentApp.root')),
            ],
            options={
                'db_table': 'request_root_map',
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['place', 'date'], name='request_place_i_7a0714_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', 'date'], name='request_user_id_f6890d_idx'),
        ),
        migrations.AddIndex(
            model_name='root',
            index=models.Index(fields=['place', 'created_at'], name='root_place_i_85056f_idx'),
        ),
        migrations.AddIndex(
            model_name='root',
            index=models.Index(fields=['founder', 'created_at'], name='root_founder_0ae9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrootmap',
            index=models.Index(fields=['request', 'acceptance'], name='request_roo_request_e9186d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrootmap',
            index=models.Index(fields=['root', 'acceptance'], name='request_roo_root_id_86a275_idx'),
        ),
    ]
