# Generated by Django 5.2.7 on 2025-11-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DocumentApp', '0001_initial'),
        ('PlaceApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestrootmap',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='DocumentApp.request'),
        ),
        migrations.AddField(
            model_name='root',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='root',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roots', to='PlaceApp.travelplace'),
        ),
        migrations.AddField(
            model_name='requestrootmap',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='DocumentApp.root'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['place', 'date'], name='request_place_i_7a0714_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', 'date'], name='request_user_id_f6890d_idx'),
        ),
        migrations.AddIndex(
            model_name='root',
            index=models.Index(fields=['place', 'created_at'], name='root_place_i_85056f_idx'),
        ),
        migrations.AddIndex(
            model_name='root',
            index=models.Index(fields=['founder', 'created_at'], name='root_founder_0ae9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrootmap',
            index=models.Index(fields=['request', 'acceptance'], name='request_roo_request_e9186d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrootmap',
            index=models.Index(fields=['root', 'acceptance'], name='request_roo_root_id_86a275_idx'),
        ),
    ]
