# Generated by Django 5.2.7 on 2025-11-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DocumentApp', '0001_initial'),
        ('PlaceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='PlaceApp.travelplace'),
        ),
    ]
