# Generated by Django 5.2.7 on 2025-11-19 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='태그 이름 (예: "여유로운 여행", "숨겨진 로컬 스팟")', max_length=100)),
                ('level', models.PositiveSmallIntegerField(help_text='계층 레벨 (1=대분류, 2=중분류, 3=소분류)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('parent', models.ForeignKey(blank=True, help_text='부모 태그 (level 1은 NULL, level 2/3은 상위 테마 태그)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='DocumentApp.themetag')),
            ],
            options={
                'verbose_name': '여행 테마 태그',
                'verbose_name_plural': '여행 테마 태그들',
                'db_table': 'theme_tag',
            },
        ),
    ]
