# Generated by Django 5.2.7 on 2025-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentApp', '0004_themetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='travel_type',
        ),
        migrations.AddField(
            model_name='request',
            name='travel_type',
            field=models.ManyToManyField(blank=True, help_text='사용자가 선택한 모든 여행 테마 태그 (level1/2/3 포함 가능)', related_name='requests', to='DocumentApp.themetag'),
        ),
    ]
