# Generated by Django 5.2.7 on 2025-11-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='여행지 이름')),
                ('photo', models.CharField(max_length=255, verbose_name='여행지 사진 url')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'db_table': 'travel_place',
                'indexes': [models.Index(fields=['name'], name='travel_plac_name_9b4c38_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('hot_id', models.BigAutoField(db_column='Hot_id', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='집계 시작일')),
                ('end_date', models.DateTimeField(verbose_name='집계 종료일')),
                ('score', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='최종 점수')),
                ('rank', models.PositiveIntegerField(verbose_name='순위')),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'hot_spot',
                'indexes': [models.Index(fields=['place', 'start_date'], name='hot_spot_place_i_ed7b15_idx'), models.Index(fields=['rank'], name='hot_spot_rank_1eb72d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='hotspot_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='TrendSpot',
            fields=[
                ('trend_id', models.BigAutoField(db_column='Trend_id', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='집계 시작일')),
                ('end_date', models.DateTimeField(verbose_name='집계 종료일')),
                ('score', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='최종 점수')),
                ('rank', models.PositiveIntegerField(verbose_name='순위')),
                ('age_group', models.CharField(choices=[('GLOBAL', 'GLOBAL'), ('10S', '10S'), ('20S', '20S'), ('30S', '30S'), ('40S', '40S'), ('50S', '50S'), ('60P', '60P'), ('UNKNOWN', 'UNKNOWN')], default='GLOBAL', max_length=10, verbose_name='나이대 세그먼트')),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='trendspots', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'trend_spot',
                'indexes': [models.Index(fields=['place', 'age_group', 'start_date'], name='trend_spot_place_i_24496f_idx'), models.Index(fields=['rank'], name='trend_spot_rank_7f329d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='trendspot_period_valid')],
            },
        ),
    ]
