# Generated by Django 5.2.7 on 2025-11-10 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendSpot',
            fields=[
                ('trend_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('GLOBAL', 'Global'), ('10S', '10대'), ('20S', '20대'), ('30S', '30대'), ('40S', '40대'), ('50S', '50대'), ('60P', '60+'), ('UNKNOWN', 'Unknown')], default='GLOBAL', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'trend_spot',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wishlist_item',
            },
        ),
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('district', models.CharField(blank=True, default='', max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'travel_place',
                'indexes': [models.Index(fields=['country', 'state', 'city', 'district'], name='travel_plac_country_a5ef64_idx'), models.Index(fields=['name'], name='travel_plac_name_9b4c38_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('hot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'hot_spot',
            },
        ),
        migrations.CreateModel(
            name='TravelPlaceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'travelplace_like',
            },
        ),
    ]
