# Generated by Django 5.2.7 on 2025-11-09 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'travel_place',
                'indexes': [models.Index(fields=['country', 'state', 'city', 'district'], name='travel_plac_country_a5ef64_idx'), models.Index(fields=['name'], name='travel_plac_name_9b4c38_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('hot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'hot_spot',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='hot_spot_start_d_1d5823_idx'), models.Index(fields=['rank'], name='hot_spot_rank_1eb72d_idx')],
                'unique_together': {('place', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='TrendSpot',
            fields=[
                ('trend_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('GLOBAL', 'Global'), ('10S', '10대'), ('20S', '20대'), ('30S', '30대'), ('40S', '40대'), ('50S', '50대'), ('60P', '60+'), ('UNKNOWN', 'Unknown')], default='GLOBAL', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trendspots', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'trend_spot',
                'indexes': [models.Index(fields=['age_group', 'start_date', 'end_date'], name='trend_spot_age_gro_c6620f_idx'), models.Index(fields=['rank'], name='trend_spot_rank_7f329d_idx')],
                'unique_together': {('place', 'age_group', 'start_date', 'end_date')},
            },
        ),
    ]
