# Generated by Django 5.2.7 on 2025-11-10 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlaceApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplacelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trendspot',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trendspots', to='PlaceApp.travelplace'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='travel_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='PlaceApp.travelplace'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='trend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='PlaceApp.trendspot'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='PlaceApp.wishlist'),
        ),
        migrations.AddIndex(
            model_name='hotspot',
            index=models.Index(fields=['start_date', 'end_date'], name='hot_spot_start_d_1d5823_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspot',
            index=models.Index(fields=['rank'], name='hot_spot_rank_1eb72d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotspot',
            unique_together={('place', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='travelplacelike',
            unique_together={('user', 'place')},
        ),
        migrations.AddIndex(
            model_name='trendspot',
            index=models.Index(fields=['age_group', 'start_date', 'end_date'], name='trend_spot_age_gro_c6620f_idx'),
        ),
        migrations.AddIndex(
            model_name='trendspot',
            index=models.Index(fields=['rank'], name='trend_spot_rank_7f329d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trendspot',
            unique_together={('place', 'age_group', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'travel_spot', 'trend')},
        ),
    ]
