# Generated by Django 3.2.25 on 2025-10-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20251028_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onboarding_interests_done',
        ),
    ]
