# Generated by Django 5.2.7 on 2025-11-14 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlaceApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelStory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('photo_url', models.URLField(blank=True, default='', max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('liked_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='PlaceApp.travelplace')),
            ],
            options={
                'db_table': 'travel_story',
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='StoryApp.travelstory')),
            ],
            options={
                'db_table': 'story_like',
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='StoryApp.travelstory')),
            ],
            options={
                'db_table': 'story_comment',
            },
        ),
        migrations.AddIndex(
            model_name='travelstory',
            index=models.Index(fields=['country', 'state', 'city', 'district', 'created_at'], name='travel_stor_country_9be259_idx'),
        ),
        migrations.AddIndex(
            model_name='travelstory',
            index=models.Index(fields=['liked_count'], name='travel_stor_liked_c_0fa93d_idx'),
        ),
        migrations.AddIndex(
            model_name='travelstory',
            index=models.Index(fields=['view_count'], name='travel_stor_view_co_d7c5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='storylike',
            index=models.Index(fields=['user', 'created_at'], name='story_like_user_id_a4d76e_idx'),
        ),
        migrations.AddIndex(
            model_name='storylike',
            index=models.Index(fields=['story', 'created_at'], name='story_like_story_i_194dff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storylike',
            unique_together={('story', 'user')},
        ),
        migrations.AddIndex(
            model_name='storycomment',
            index=models.Index(fields=['story', 'created_at'], name='story_comme_story_i_66514f_idx'),
        ),
    ]
